mod: バージョンコードを自動生成するように変更

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -92,17 +92,26 @@ workflows:
       - name: Lint App
         script: |
           ./gradlew app:lintProductRelease
-      - name: Build Android App For aab
+      - name: Build Android App For aab with update build number
         script: |
-          ./gradlew app:bundleProductRelease
-      - name: Build Android App For apk
-        script: |
-          ./gradlew app:assembleProductRelease
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]
+            then
+              # fallback in case no build number was found from Google Play.
+              # Alternatively, you can `exit 1` to fail the build
+              # BUILD_NUMBER is a Codemagic built-in variable tracking the number of
+              # times this workflow has been built
+              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+            else
+              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+          fi
+
+          # "1.0.x"のようなバージョン名はbuild.gradle.ktsで自前で管理する。
+          ./gradlew bundleProductRelease -PversionCode=$UPDATED_BUILD_NUMBER
     artifacts:
       - app/build/outputs/bundle/productRelease/*
       - app/build/outputs/mapping/productRelease/*
       - app/build/intermediates/stripped_native_libs/productRelease/stripProductReleaseDebugSymbols/out/lib
-      #- app/build/outputs/apk/product/release/*
     publishing:
       email:
         recipients:
